# Generated by Django 2.1.7 on 2019-04-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='time',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
